import type { Metadata } from "next";
import { Inter, Syne, Orbitron } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import SmoothScroll from "@/components/smooth-scroll";
import Background from "@/components/background";
import Nav from "@/components/nav";
import Footer from "@/components/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
  display: "swap",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "HyperNova Technologies — We build digital things that actually work.",
  description:
    "We design and develop websites, apps, and digital experiences for founders, brands, and businesses ready to grow.",
  keywords: ["web development", "digital studio", "web apps", "mobile apps", "digital cards"],
  metadataBase: new URL("https://hypernova-website.vercel.app"),
  icons: {
    icon: "/logo.png",
  },
  openGraph: {
    title: "HyperNova Technologies — We build digital things that actually work.",
    description:
      "We design and develop websites, apps, and digital experiences for founders, brands, and businesses ready to grow.",
    url: "https://hypernova-website.vercel.app",
    siteName: "HyperNova Technologies",
    // OG image is generated by app/opengraph-image.tsx (1200×630) and wired
    // automatically by Next's file convention for both OG and Twitter.
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "HyperNova Technologies — We build digital things that actually work.",
    description:
      "We design and develop websites, apps, and digital experiences for founders, brands, and businesses ready to grow.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${syne.variable} ${orbitron.variable}`}>
      <body className="antialiased bg-bg text-primary font-sans">
        <SmoothScroll>
          {/* Persistent shell — shader, nav and footer live outside the
              per-route <template>, so they never re-mount or re-animate on
              navigation, and the shader keeps a single mount site-wide. */}
          <Background />
          <Nav />
          <main className="relative z-10 min-h-screen text-primary overflow-x-hidden">
            {children}
            <Footer />
          </main>
        </SmoothScroll>
        <Analytics />
      </body>
    </html>
  );
}
